/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 21 Apr 2022 14:02:41 GMT'
 */
export const projectModel = {
  languages: {
    default: {
      codename: 'default',
      name: 'Default project language',
    },
  },
  contentTypes: {
    call_to_action: {
      codename: 'call_to_action',
      name: 'Call to Action',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        button_image: {
          codename: 'button_image',
          name: 'Button Image',
        },
        button_text: {
          codename: 'button_text',
          name: 'Button Text',
        },
        subheading: {
          codename: 'subheading',
          name: 'Subheading',
        },
        button_link: {
          codename: 'button_link',
          name: 'Button Link',
        },
      },
    },
    hero: {
      codename: 'hero',
      name: 'Hero',
      elements: {
        personalization_criteria: {
          codename: 'personalization_criteria',
          name: 'Personalization Criteria',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        button_text: {
          codename: 'button_text',
          name: 'Button Text',
        },
        button_link_slug: {
          codename: 'button_link_slug',
          name: 'Button Link Slug',
        },
      },
    },
    page: {
      codename: 'page',
      name: 'Page',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        components: {
          codename: 'components',
          name: 'Components',
        },
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        enrichment_tags: {
          codename: 'enrichment_tags',
          name: 'Enrichment tags',
        },
      },
    },
    personalized_heroes: {
      codename: 'personalized_heroes',
      name: 'Personalized Heroes',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        personalized_heroes_list: {
          codename: 'personalized_heroes_list',
          name: 'Personalized Heroes List',
        },
      },
    },
    personalized_talks_lists: {
      codename: 'personalized_talks_lists',
      name: 'Personalized Talks Lists',
      elements: {
        personalized_talks_lists_list: {
          codename: 'personalized_talks_lists_list',
          name: 'Personalized Talks Lists List',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    registration_form: {
      codename: 'registration_form',
      name: 'Registration Form',
      elements: {
        button_text: {
          codename: 'button_text',
          name: 'Button Text',
        },
        registered_text: {
          codename: 'registered_text',
          name: 'Registered Text',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    talk: {
      codename: 'talk',
      name: 'Talk',
      elements: {
        audience: {
          codename: 'audience',
          name: 'Audience',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    talks_list: {
      codename: 'talks_list',
      name: 'Talks List',
      elements: {
        register_button_text: {
          codename: 'register_button_text',
          name: 'Register Button Text',
        },
        talks: {
          codename: 'talks',
          name: 'Talks',
        },
        number_to_show: {
          codename: 'number_to_show',
          name: 'Number to Show',
        },
        personalization_criteria: {
          codename: 'personalization_criteria',
          name: 'Personalization Criteria',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        title_when_personalized: {
          codename: 'title_when_personalized',
          name: 'Title when Personalized',
        },
      },
    },
    why_attend: {
      codename: 'why_attend',
      name: 'Why Attend',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
      },
    },
  },
  taxonomies: {},
};
