import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0' at 'Thu, 21 Apr 2022 14:02:41 GMT'
 */
export type CallToAction = IContentItem<{
  title: Elements.TextElement;
  buttonImage: Elements.AssetsElement;
  buttonText: Elements.TextElement;
  subheading: Elements.TextElement;
  buttonLink: Elements.TextElement;
}>;
